name = "rona-appointment"
main = ".open-next/worker.js"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build:cf"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "rona-appointments-db"
database_id = "ae06ce9b-4575-4f03-a6b1-5451a3b87161"

[observability.logs]
enabled = false
head_sampling_rate = 1
invocation_logs = true
persist = true
